### ISSUE TITLE
$entries variable not available

### ISSUE THREAD

**Issue by EmanueleCoppola** [Laravel-Backpack/CRUD#1082]
For some reason using the dev-upgrade, using a custom list view:
```
$this->crud->setListView('custom.condo_ticket.list.list');
```
It's not available anymore the $entries variable even if Ajax is disabled, but rolling it back to ^3.2.0 all works fine.

Maybe in the upgrate something got broke.

**Comment by lloy0076** [comment]
Anything in `storage/logs/laravel.log` that might hint at something awry?

**Comment by EmanueleCoppola** [comment]
This is all I get from laravel while using upgrade branch
```
[2017-10-27 08:05:35] local.ERROR: Undefined variable: entries (View: C:\Users\Manu\PhpstormProjects\geclone-condomini-ng\resources\views\custom\condo_ticket\list\list.blade.php) {"exception":"[object] (ErrorException(code: 0): Undefined variable: entries (View: C:\\Users\\Manu\\PhpstormProjects\\geclone-condomini-ng\
esources\\views\\custom\\condo_ticket\\list\\list.blade.php) at C:\\Users\\Manu\\PhpstormProjects\\geclone-condomini-ng\\storage\\framework\\views\\f8d5d1477c1d8c4a266512caac92bd201119f0e9.php:26, ErrorException(code: 0): Undefined variable: entries at C:\\Users\\Manu\\PhpstormProjects\\geclone-condomini-ng\\storage\\framework\\views\\f8d5d1477c1d8c4a266512caac92bd201119f0e9.php:26)
[stacktrace]
#0 C:\\Users\\Manu\\PhpstormProjects\\geclone-condomini-ng\\vendor\\laravel\\framework\\src\\Illuminate\\View\\Engines\\PhpEngine.php(45): Illuminate\\View\\Engines\\CompilerEngine->handleViewException(Object(ErrorException), 1)
#1 C:\\Users\\Manu\\PhpstormProjects\\geclone-condomini-ng\\vendor\\laravel\\framework\\src\\Illuminate\\View\\Engines\\CompilerEngine.php(59): Illuminate\\View\\Engines\\PhpEngine->evaluatePath('C:\\\\Users\\\\Manu\\\\P...', Array)
#2 C:\\Users\\Manu\\PhpstormProjects\\geclone-condomini-ng\\vendor\\laravel\\framework\\src\\Illuminate\\View\\View.php(137): Illuminate\\View\\Engines\\CompilerEngine->get('C:\\\\Users\\\\Manu\\\\P...', Array)
#3 C:\\Users\\Manu\\PhpstormProjects\\geclone-condomini-ng\\vendor\\laravel\\framework\\src\\Illuminate\\View\\View.php(120): Illuminate\\View\\View->getContents()
#4 C:\\Users\\Manu\\PhpstormProjects\\geclone-condomini-ng\\vendor\\laravel\\framework\\src\\Illuminate\\View\\View.php(85): Illuminate\\View\\View->renderContents()
#5 C:\\Users\\Manu\\PhpstormProjects\\geclone-condomini-ng\\vendor\\laravel\\framework\\src\\Illuminate\\Http\\Response.php(42): Illuminate\\View\\View->render()
#6 C:\\Users\\Manu\\PhpstormProjects\\geclone-condomini-ng\\vendor\\symfony\\http-foundation\\Response.php(199): Illuminate\\Http\\Response->setContent(Object(Illuminate\\View\\View))
#7 C:\\Users\\Manu\\PhpstormProjects\\geclone-condomini-ng\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(711): Symfony\\Component\\HttpFoundation\\Response->__construct(Object(Illuminate\\View\\View))
#8 C:\\Users\\Manu\\PhpstormProjects\\geclone-condomini-ng\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(685): Illuminate\\Routing\\Router::toResponse(Object(Illuminate\\Http\\Request), Object(Illuminate\\View\\View))
#9 C:\\Users\\Manu\\PhpstormProjects\\geclone-condomini-ng\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(645): Illuminate\\Routing\\Router->prepareResponse(Object(Illuminate\\Http\\Request), Object(Illuminate\\View\\View))
#10 C:\\Users\\Manu\\PhpstormProjects\\geclone-condomini-ng\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(30): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#11 C:\\Users\\Manu\\PhpstormProjects\\geclone-condomini-ng\\vendor\\backpack\\crud\\src\\app\\Http\\Controllers\\CrudController.php(41): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#12 C:\\Users\\Manu\\PhpstormProjects\\geclone-condomini-ng\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(131): Backpack\\CRUD\\app\\Http\\Controllers\\CrudController->Backpack\\CRUD\\app\\Http\\Controllers\\{closure}(Object(Illuminate\\Http\\Request), Object(Closure))
#13 C:\\Users\\Manu\\PhpstormProjects\\geclone-condomini-ng\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#14 C:\\Users\\Manu\\PhpstormProjects\\geclone-condomini-ng\\app\\Http\\Middleware\\Admin.php(32): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#15 C:\\Users\\Manu\\PhpstormProjects\\geclone-condomini-ng\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(149): App\\Http\\Middleware\\Admin->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#16 C:\\Users\\Manu\\PhpstormProjects\\geclone-condomini-ng\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#17 C:\\Users\\Manu\\PhpstormProjects\\geclone-condomini-ng\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Middleware\\SubstituteBindings.php(41): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#18 C:\\Users\\Manu\\PhpstormProjects\\geclone-condomini-ng\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(149): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#19 C:\\Users\\Manu\\PhpstormProjects\\geclone-condomini-ng\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#20 C:\\Users\\Manu\\PhpstormProjects\\geclone-condomini-ng\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken.php(67): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#21 C:\\Users\\Manu\\PhpstormProjects\\geclone-condomini-ng\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#22 C:\\Users\\Manu\\PhpstormProjects\\geclone-condomini-ng\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#23 C:\\Users\\Manu\\PhpstormProjects\\geclone-condomini-ng\\vendor\\laravel\\framework\\src\\Illuminate\\View\\Middleware\\ShareErrorsFromSession.php(49): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#24 C:\\Users\\Manu\\PhpstormProjects\\geclone-condomini-ng\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(149): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#25 C:\\Users\\Manu\\PhpstormProjects\\geclone-condomini-ng\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#26 C:\\Users\\Manu\\PhpstormProjects\\geclone-condomini-ng\\vendor\\laravel\\framework\\src\\Illuminate\\Session\\Middleware\\StartSession.php(63): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#27 C:\\Users\\Manu\\PhpstormProjects\\geclone-condomini-ng\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(149): Illuminate\\Session\\Middleware\\StartSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#28 C:\\Users\\Manu\\PhpstormProjects\\geclone-condomini-ng\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#29 C:\\Users\\Manu\\PhpstormProjects\\geclone-condomini-ng\\vendor\\laravel\\framework\\src\\Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse.php(37): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#30 C:\\Users\\Manu\\PhpstormProjects\\geclone-condomini-ng\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(149): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#31 C:\\Users\\Manu\\PhpstormProjects\\geclone-condomini-ng\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#32 C:\\Users\\Manu\\PhpstormProjects\\geclone-condomini-ng\\vendor\\laravel\\framework\\src\\Illuminate\\Cookie\\Middleware\\EncryptCookies.php(59): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#33 C:\\Users\\Manu\\PhpstormProjects\\geclone-condomini-ng\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(149): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#34 C:\\Users\\Manu\\PhpstormProjects\\geclone-condomini-ng\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#35 C:\\Users\\Manu\\PhpstormProjects\\geclone-condomini-ng\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(102): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#36 C:\\Users\\Manu\\PhpstormProjects\\geclone-condomini-ng\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(647): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#37 C:\\Users\\Manu\\PhpstormProjects\\geclone-condomini-ng\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(622): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#38 C:\\Users\\Manu\\PhpstormProjects\\geclone-condomini-ng\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(588): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#39 C:\\Users\\Manu\\PhpstormProjects\\geclone-condomini-ng\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(577): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#40 C:\\Users\\Manu\\PhpstormProjects\\geclone-condomini-ng\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(176): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#41 C:\\Users\\Manu\\PhpstormProjects\\geclone-condomini-ng\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(30): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#42 C:\\Users\\Manu\\PhpstormProjects\\geclone-condomini-ng\\vendor\\barryvdh\\laravel-debugbar\\src\\Middleware\\InjectDebugbar.php(65): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#43 C:\\Users\\Manu\\PhpstormProjects\\geclone-condomini-ng\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(149): Barryvdh\\Debugbar\\Middleware\\InjectDebugbar->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#44 C:\\Users\\Manu\\PhpstormProjects\\geclone-condomini-ng\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#45 C:\\Users\\Manu\\PhpstormProjects\\geclone-condomini-ng\\vendor\\fideloper\\proxy\\src\\TrustProxies.php(56): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#46 C:\\Users\\Manu\\PhpstormProjects\\geclone-condomini-ng\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(149): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#47 C:\\Users\\Manu\\PhpstormProjects\\geclone-condomini-ng\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#48 C:\\Users\\Manu\\PhpstormProjects\\geclone-condomini-ng\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest.php(30): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#49 C:\\Users\\Manu\\PhpstormProjects\\geclone-condomini-ng\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#50 C:\\Users\\Manu\\PhpstormProjects\\geclone-condomini-ng\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#51 C:\\Users\\Manu\\PhpstormProjects\\geclone-condomini-ng\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest.php(30): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#52 C:\\Users\\Manu\\PhpstormProjects\\geclone-condomini-ng\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#53 C:\\Users\\Manu\\PhpstormProjects\\geclone-condomini-ng\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#54 C:\\Users\\Manu\\PhpstormProjects\\geclone-condomini-ng\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize.php(27): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#55 C:\\Users\\Manu\\PhpstormProjects\\geclone-condomini-ng\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#56 C:\\Users\\Manu\\PhpstormProjects\\geclone-condomini-ng\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#57 C:\\Users\\Manu\\PhpstormProjects\\geclone-condomini-ng\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode.php(46): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#58 C:\\Users\\Manu\\PhpstormProjects\\geclone-condomini-ng\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#59 C:\\Users\\Manu\\PhpstormProjects\\geclone-condomini-ng\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#60 C:\\Users\\Manu\\PhpstormProjects\\geclone-condomini-ng\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(102): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#61 C:\\Users\\Manu\\PhpstormProjects\\geclone-condomini-ng\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(151): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#62 C:\\Users\\Manu\\PhpstormProjects\\geclone-condomini-ng\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(116): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#63 C:\\Users\\Manu\\PhpstormProjects\\geclone-condomini-ng\\public\\index.php(55): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#64 {main}
"} 
```

**Comment by tabacitu** [comment]
Hi @EmanueleCoppola ,

This is intentional - in 3.3 **all tables are AjaxDataTables**. So yes, the ```list.blade.php``` file no longer has any ```$entries```. They're pulled in using AJAX, after pageload. If you're using a custom ```list.blade.php``` file, I recommend you **remove any code that is still there for non-ajax tables**. I'm 99% sure that's what's causing the error.

[Here's what has changed in the update](https://github.com/Laravel-Backpack/CRUD/pull/1022/files#diff-a5044a994cc483a0b10086f52ad4678d) - you can make the same modifs to your view too.

Hope it helps.
Cheers!

**Comment by EmanueleCoppola** [comment]
So what if I want to create a custom layour for listing my entries?

**Comment by tabacitu** [comment]
@EmanueleCoppola sure, you can do that. You can use ```$this->crud->setListView()``` in your EntityCrudController and you'd only be using that view for that entity.

https://laravel-backpack.readme.io/docs/crud-full-api#section-sometimes-used
