### ISSUE TITLE
Re-order Operation throws JS errors. Specifically in Backpack V5

### ISSUE THREAD

**Issue by karandatwani92** [Laravel-Backpack/CRUD#4215]
# Bug report

### What I did

Tried Reorder operation using Custom CRUD, Menu CRUD(Add ON).

### What happened
 Throws JS Error
 `jquery-ui.min.js:1 Uncaught TypeError: Cannot read properties of undefined (reading 'vertical')
    at t.<computed>.<computed>._intersectsWithPointer (jquery-ui.min.js:1:213977)
    at t.<computed>.<computed>.t.each.r.<computed> (jquery-ui.min.js:1:1334)
    at t.<computed>.<computed>.t.each.r.<computed> [as _intersectsWithPointer] (jquery-ui.min.js:1:1334)
    at t.<computed>.<computed>._mouseDrag (jquery.mjs.nestedSortable2.js:273:25)
    at t.<computed>.<computed>.t.each.r.<computed> [as _mouseDrag] (jquery-ui.min.js:1:1334)
    at t.<computed>.<computed>._mouseStart (jquery-ui.min.js:1:208437)
    at t.<computed>.<computed>.t.each.r.<computed> (jquery-ui.min.js:1:1334)
    at t.<computed>.<computed>.t.each.r.<computed> [as _mouseStart] (jquery-ui.min.js:1:1334)
    at t.<computed>.<computed>._mouseMove (jquery-ui.min.js:1:121843)
    at t.<computed>.<computed>.t.each.r.<computed> (jquery-ui.min.js:1:1334)`

### What I've already tried to fix it
Tried Fresh Installation. Same Error in Backpack V5

Perfectly Works in Backpack V4.1

### Is it a bug in the latest version of Backpack?
Yes, Tried Fresh Installation. Same Error in Backpack V5
Perfectly Works in Backpack V4.1
After I run ```composer update backpack/crud``` the bug... is it still there?
Yes

### PHP VERSION:
PHP 7.4.16 (cli) (built: Mar  2 2021 14:06:15) ( ZTS Visual C++ 2017 x64 )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies

### LARAVEL VERSION:
v8.83.1@bddba117f8bce2f3c9875ca1ca375a96350d0f4d

### BACKPACK VERSION:
5.0.0@c4eb4aeb55dfaf29ecd3f5e0e35ba4321d9c004a

**Comment by karandatwani92** [comment]
Hello @tabacitu ,

I Re-tried it by **replacing following JS files from your demo link and it worked.**
packages/jquery-ui-dist/jquery-ui.min.js
packages/nestedSortable/jquery.mjs.nestedSortable2.js

**Comment by tabacitu** [comment]
Hi @karandatwani92 ,

Indeed, there was an incompatibility issue with nestedSortable, that we fixed in 5.0.4: https://github.com/Laravel-Backpack/CRUD/releases/tag/5.0.4

But if you've already done the above, you don't have to do anything.

Cheers!
